- position: [6, -27, 3] # on the road
- position: [26, -38, 3] # 
- position: [27, -22, 3] # back in the firehygrant`
- position: [0, 0, 3]
- position: [6, -27, 3] # on the road
- position: [26, -38, 3] # 
- position: [27, -22, 3] # back in the firehygrant`
- position: [0, 0, 3]
- position: [6, -27, 3] # on the road
- position: [26, -38, 3] # 
- position: [27, -22, 3] # back in the firehygrant`
- position: [0, 0, 3]
# - position: [31, -7, 3] # back in the firehygrant`
