name: docker-build-estimation

# Build estimation when "base" changes, or when any files in the estimation
# folder are modified
on:
  workflow_run:
    workflows: ["docker-build-base"]
    branches: [master]
    types:
      - completed
  push:
    paths:
    - 'autonomy_core/estimation/**'
    branches: [master]
  workflow_dispatch:
  # DO NOT add a schedule. This build will be triggered by base schedule.

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kumarrobotics/autonomy:estimation
          file: ./autonomy_core/estimation/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
