name: docker-build-base

# Only build base when any of the files in the base directory are modified
on:
  push:
    paths:
    - 'autonomy_core/base/**'
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kumarrobotics/autonomy:base
          file: ./autonomy_core/base/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
